root: ./
structure:
  summary: SUMMARY.md  # 目录文件
  readme: README.md  # 主页文件
  languages: LANGS.md  # 多语言支持（如果有）

title: "Java 学习笔记"  # GitBook 站点名称
author: "你的名字"
description: "一本包含 Java 相关知识的 GitBook"

# 目录映射
pages:
  - path: zh/Java基础
    title: "Java 基础"
  - path: en/Java基础
    title: "Java Basics"

plugins:
  - anchors
  - highlight
  - search
  - prism

pdf:
  pageNumbers: true
  fontSize: 12pt
  paperSize: a4

theme: "light"